export default {
  appName: 'AGENSY', welcomeEyebrow: 'AGENSY AFRICA', welcomeTitle: 'Supply you can count on.', welcomeText: 'Reliable products, guaranteed prices and tracked delivery, wherever your business goes.', getStarted: 'Get started', alreadyAccount: 'I already have an account',
  phoneTitle: 'Your WhatsApp number', phoneText: 'Select your country code and enter your number to receive a verification code.', phoneLabel: 'WhatsApp number', continue: 'Continue', otpTitle: 'Verify your number', otpText: 'Enter the 4-digit code sent to WhatsApp.', otpLabel: 'Verification code', verify: 'Verify', resend: 'Resend code', demoHint: 'In demo mode, use the code displayed.',
  profileTitle: 'Tell us about your business', profileText: 'This information helps us prepare your orders and invoices.', businessName: 'Business name', managerName: 'Manager name', businessType: 'Business type', country: 'Country', ncc: 'Taxpayer account number (NCC)', formal: 'Formal business', informal: 'Informal business', saveProfile: 'Save my profile', profileRequired: 'Please complete the required fields.',
  greeting: 'Hello', home: 'Home', catalog: 'Catalog', order: 'Order', tracking: 'Tracking', account: 'Account', newOrder: 'New order', heroTitle: 'Supply without surprises.', heroText: 'Selected products, guaranteed monthly prices and integrated delivery.', availableProducts: 'Available products', recentOrders: 'Recent orders', seeAll: 'See all', search: 'Search products', monthlyGuarantee: 'Price guaranteed this month', noProducts: 'No products match your search.',
  orderDetails: 'Your order', quantity: 'Quantity', minimum: 'Minimum', productSubtotal: 'Products subtotal', serviceFee: 'Agensy service fee', delivery: 'Delivery', toConfirm: 'To be confirmed', estimatedTotal: 'Estimated total', deliveryNote: 'A team member will confirm the delivery amount and date before payment.', deliveryAddress: 'Delivery address', deliveryPlaceholder: 'E.g. Cocody, Abidjan', instructions: 'Delivery instructions', instructionsPlaceholder: 'E.g. Call before delivery', when: 'When would you like delivery?', asap: 'As soon as possible', scheduled: 'On a specific date', recurring: 'Recurring', weekly: 'Every week', monthly: 'Every month', sendOrder: 'Send order', orderSent: 'Order sent', orderSentText: 'Agensy will respond within 24 hours. You will be notified here and on WhatsApp.',
  myOrders: 'My orders', noOrders: 'You have no orders yet.', startOrder: 'Create an order', draft: 'Draft', submitted: 'Sent', adjusted: 'Adjusted', accepted: 'Accepted', paid: 'Paid', delivered: 'Delivered', cancelled: 'Cancelled', awaitingValidation: 'Agensy validation in progress', payNow: 'Pay now', paymentAvailable: 'Your Jeko payment link is available.', trackOrder: 'Track order', cancelOrder: 'Cancel order', cancelConfirm: 'Would you like to cancel this order?', orderCancelled: 'Order cancelled',
  notifications: 'Notifications', noNotifications: 'No notifications yet.', markAllRead: 'Mark all as read', invoices: 'FNE invoices', noInvoices: 'Your certified invoices will appear here.', downloadInvoice: 'Download PDF', accountTitle: 'Your business', profileIncomplete: 'Profile incomplete', businessInformation: 'Business information', notificationPrefs: 'Notifications and WhatsApp', languageCurrency: 'Language and currency', help: 'Help', signOut: 'Sign out', language: 'Language', currency: 'Display currency', french: 'French', english: 'English', xof: 'CFA franc (XOF)', eur: 'Euro (EUR)', usd: 'US dollar (USD)', save: 'Save', close: 'Close',
  error: 'Something went wrong', networkError: 'Agensy could not be reached. Check your connection.', required: 'This field is required.', pricePer: '{{price}}/{{unit}}', orderCount: '{{count}} order', orderCount_plural: '{{count}} orders',
  phonePlaceholder: '07 00 00 00 00', phoneHint: 'Use the number that will receive order confirmations.', countryCode: 'Country code', otpHint: 'Enter one digit in each box.', otpDigit: 'Code digit {{number}}', mapboxUnavailable: 'Address search will be enabled in the mobile version with the Mapbox key.',
  partner: 'partner', accountWelcomeTitle: 'Welcome, {{name}}!', accountWelcomeText: 'Your business account is ready. You can now browse the catalogue, prepare your first order and track deliveries.', deliveryAddressSaved: 'Delivery address saved', whatsAppEnabled: 'WhatsApp notifications enabled', b2bInvoicingReady: 'B2B invoicing prepared', browseCatalogue: 'Browse catalogue', goToHome: 'Go to my home',
  profileStepBusiness: 'Business', profileStepContact: 'Contact', profileStepDelivery: 'Delivery', profileStepBilling: 'Billing', requiredFields: 'Required fields', completeStep: 'Complete the fields on this step.', setupBusinessAccount: 'Set up your business account', setupBusinessAccountText: 'Four short steps to prepare orders, deliveries and invoices.', yourBusiness: 'Your business', businessNameRequired: 'Business name *', businessNamePlaceholder: 'e.g. Chez Awa restaurant', businessTypeRequired: 'Business type *', businessStatusRequired: 'Business status *', businessTypeShop: 'Shop', businessTypeRestaurant: 'Restaurant', businessTypeHotel: 'Hotel', businessTypeCanteen: 'Canteen', businessTypeReseller: 'Reseller',
  accountManager: 'Account manager', fullNameRequired: 'Full name *', fullNamePlaceholder: 'e.g. Awa Koné', roleRequired: 'Role *', rolePlaceholder: 'e.g. Manager, buyer, owner', businessEmailOptional: 'Business email (optional)', businessEmailPlaceholder: 'contact@entreprise.com', verifiedWhatsAppHint: 'The verified WhatsApp number will receive notifications.', usualDeliveryAddress: 'Usual delivery address', deliveryAreaRequired: 'Delivery area *', ivoryCoast: 'Côte d’Ivoire', international: 'International', locating: 'Locating…', locateBusiness: 'Locate my business on the map', cityRequired: 'City *', cityPlaceholder: 'e.g. Abidjan', addressDistrictRequired: 'Address / district *', addressDistrictPlaceholder: 'Search an address or district', landmarkOptional: 'Landmark (optional)', landmarkPlaceholder: 'e.g. Opposite the pharmacy',
  billingInformation: 'Billing information', nccRequired: 'NCC *', nccPlaceholder: 'Taxpayer account number', nccHint: 'The taxpayer number is required for Ivorian B2B invoicing and will be verified before FNE issuance.', taxIdRequired: 'Tax or company registration ID *', taxIdPlaceholder: 'Your country identifier', billingCountryRequired: 'Billing country *', billingCountryPlaceholder: 'e.g. Senegal', back: 'Back', finishProfile: 'Finish profile', invalidWhatsAppNumber: 'Enter a valid country code and WhatsApp number.', locationPermissionRequired: 'Allow location access to place your business on the map.', locationNotFound: 'The business location could not be found. Check GPS and try again.', deliveryDateRequired: 'Choose a delivery date.', quantityRange: 'Min. {{min}} · Max. {{max}}', preferredDateRequired: 'Preferred date (DD/MM/YYYY) *', datePlaceholder: '25/08/2026', frequency: 'Frequency', editBusinessProfile: 'Edit business profile', decreaseQuantity: 'Decrease quantity', increaseQuantity: 'Increase quantity'
};
