export default {
  appName: 'AGENSY', welcomeEyebrow: 'AGENSY AFRICA', welcomeTitle: 'L’approvisionnement qui tient parole.', welcomeText: 'Des produits fiables, des prix garantis et une livraison suivie, partout où votre commerce avance.', getStarted: 'Commencer', alreadyAccount: 'J’ai déjà un compte',
  phoneTitle: 'Votre numéro WhatsApp', phoneText: 'Choisissez votre indicatif puis saisissez votre numéro pour recevoir un code de vérification.', phoneLabel: 'Numéro WhatsApp', continue: 'Continuer', otpTitle: 'Vérifiez votre numéro', otpText: 'Saisissez le code à 4 chiffres envoyé sur WhatsApp.', otpLabel: 'Code de vérification', verify: 'Vérifier', resend: 'Renvoyer le code', demoHint: 'En démo, utilisez le code affiché.',
  profileTitle: 'Parlons de votre commerce', profileText: 'Ces informations permettent de préparer vos commandes et vos factures.', businessName: 'Nom du commerce', managerName: 'Nom du responsable', businessType: 'Type de commerce', country: 'Pays', ncc: 'Numéro de compte contribuable (NCC)', formal: 'Commerce formel', informal: 'Commerce informel', saveProfile: 'Enregistrer mon profil', profileRequired: 'Veuillez renseigner les champs obligatoires.',
  greeting: 'Bonjour', home: 'Accueil', catalog: 'Catalogue', order: 'Commande', tracking: 'Suivi', account: 'Compte', newOrder: 'Nouvelle commande', heroTitle: 'Votre approvisionnement, sans surprise.', heroText: 'Produits sélectionnés, prix mensuels garantis, livraison intégrée.', availableProducts: 'Produits disponibles', recentOrders: 'Commandes récentes', seeAll: 'Voir toutes', search: 'Rechercher un produit', monthlyGuarantee: 'Prix garanti ce mois', noProducts: 'Aucun produit ne correspond à votre recherche.',
  orderDetails: 'Votre commande', quantity: 'Quantité', minimum: 'Minimum', productSubtotal: 'Sous-total produits', serviceFee: 'Frais de service Agensy', delivery: 'Livraison', toConfirm: 'À confirmer', estimatedTotal: 'Total estimatif', deliveryNote: 'Le montant et la date de livraison seront confirmés par un opérateur avant paiement.', deliveryAddress: 'Adresse de livraison', deliveryPlaceholder: 'Ex. Cocody, Abidjan', instructions: 'Instructions de livraison', instructionsPlaceholder: 'Ex. Appelez avant de livrer', when: 'Quand souhaitez-vous être livré ?', asap: 'Dès que possible', scheduled: 'À une date précise', recurring: 'Récurrente', weekly: 'Chaque semaine', monthly: 'Chaque mois', sendOrder: 'Envoyer la commande', orderSent: 'Commande envoyée', orderSentText: 'Agensy répondra sous 24 heures. Vous serez informé ici et sur WhatsApp.',
  myOrders: 'Mes commandes', noOrders: 'Vous n’avez pas encore de commande.', startOrder: 'Créer une commande', draft: 'Brouillon', submitted: 'Envoyée', adjusted: 'Ajustée', accepted: 'Acceptée', paid: 'Payée', delivered: 'Livrée', cancelled: 'Annulée', awaitingValidation: 'Validation Agensy en cours', payNow: 'Payer maintenant', paymentAvailable: 'Votre lien Jeko est disponible.', trackOrder: 'Suivre la commande', cancelOrder: 'Annuler la commande', cancelConfirm: 'Voulez-vous annuler cette commande ?', orderCancelled: 'Commande annulée',
  notifications: 'Notifications', noNotifications: 'Aucune notification pour le moment.', markAllRead: 'Tout marquer comme lu', invoices: 'Factures FNE', noInvoices: 'Vos factures certifiées apparaîtront ici.', downloadInvoice: 'Télécharger le PDF', accountTitle: 'Votre commerce', profileIncomplete: 'Profil à compléter', businessInformation: 'Informations du commerce', notificationPrefs: 'Notifications et WhatsApp', languageCurrency: 'Langue et devise', help: 'Aide', signOut: 'Se déconnecter', language: 'Langue', currency: 'Devise d’affichage', french: 'Français', english: 'English', xof: 'Franc CFA (XOF)', eur: 'Euro (EUR)', usd: 'Dollar US (USD)', save: 'Enregistrer', close: 'Fermer',
  error: 'Une erreur est survenue', networkError: 'Impossible de joindre Agensy. Vérifiez votre connexion.', required: 'Ce champ est requis.', pricePer: '{{price}}/{{unit}}', orderCount: '{{count}} commande', orderCount_plural: '{{count}} commandes',
  phonePlaceholder: '07 00 00 00 00', phoneHint: 'Utilisez le numéro qui recevra les confirmations de commande.', countryCode: 'Indicatif du pays', otpHint: 'Chaque chiffre va dans sa propre case.', otpDigit: 'Chiffre {{number}} du code', mapboxUnavailable: 'La recherche d’adresse sera activée dans la version mobile avec la clé Mapbox.',
  partner: 'partenaire', accountWelcomeTitle: 'Bienvenue, {{name}} !', accountWelcomeText: 'Votre compte professionnel est prêt. Vous pouvez maintenant consulter le catalogue, préparer votre première commande et suivre vos livraisons.', deliveryAddressSaved: 'Adresse de livraison enregistrée', whatsAppEnabled: 'Notifications WhatsApp activées', b2bInvoicingReady: 'Facturation B2B préparée', browseCatalogue: 'Découvrir le catalogue', goToHome: 'Aller à mon accueil',
  profileStepBusiness: 'Commerce', profileStepContact: 'Responsable', profileStepDelivery: 'Livraison', profileStepBilling: 'Facturation', requiredFields: 'Champs requis', completeStep: 'Complétez les champs de cette étape.', setupBusinessAccount: 'Créons votre compte professionnel', setupBusinessAccountText: '4 étapes courtes pour préparer vos commandes, livraisons et factures.', yourBusiness: 'Votre commerce', businessNameRequired: 'Nom du commerce *', businessNamePlaceholder: 'Ex. Maquis Chez Awa', businessTypeRequired: 'Type de commerce *', businessStatusRequired: 'Statut du commerce *', businessTypeShop: 'Boutique', businessTypeRestaurant: 'Restaurant / maquis', businessTypeHotel: 'Hôtel', businessTypeCanteen: 'Cantine', businessTypeReseller: 'Revendeur',
  accountManager: 'Responsable du compte', fullNameRequired: 'Nom et prénom *', fullNamePlaceholder: 'Ex. Awa Koné', roleRequired: 'Fonction *', rolePlaceholder: 'Ex. Gérante, acheteur, directeur', businessEmailOptional: 'E-mail professionnel (optionnel)', businessEmailPlaceholder: 'contact@entreprise.com', verifiedWhatsAppHint: 'Le numéro WhatsApp vérifié sera utilisé pour les notifications.', usualDeliveryAddress: 'Adresse de livraison habituelle', deliveryAreaRequired: 'Zone de livraison *', ivoryCoast: 'Côte d’Ivoire', international: 'International', locating: 'Localisation en cours…', locateBusiness: 'Me localiser sur la carte', cityRequired: 'Ville *', cityPlaceholder: 'Ex. Abidjan', addressDistrictRequired: 'Adresse / quartier *', addressDistrictPlaceholder: 'Recherchez une adresse ou un quartier', landmarkOptional: 'Repère (optionnel)', landmarkPlaceholder: 'Ex. En face de la pharmacie',
  billingInformation: 'Informations de facturation', nccRequired: 'NCC *', nccPlaceholder: 'Numéro de compte contribuable', nccHint: 'Le NCC est requis pour la facture B2B ivoirienne. Il sera vérifié avant l’émission FNE.', taxIdRequired: 'Identifiant fiscal ou registre de commerce *', taxIdPlaceholder: 'Identifiant de votre pays', billingCountryRequired: 'Pays de facturation *', billingCountryPlaceholder: 'Ex. Sénégal', back: 'Retour', finishProfile: 'Terminer mon profil', invalidWhatsAppNumber: 'Saisissez un indicatif et un numéro WhatsApp valides.', locationPermissionRequired: 'Autorisez la localisation pour placer votre commerce sur la carte.', locationNotFound: 'La position du commerce est introuvable. Vérifiez le GPS puis réessayez.', deliveryDateRequired: 'Indiquez une date de livraison.', quantityRange: 'Min. {{min}} · Max. {{max}}', preferredDateRequired: 'Date souhaitée (JJ/MM/AAAA) *', datePlaceholder: '25/08/2026', frequency: 'Fréquence', editBusinessProfile: 'Modifier le profil entreprise', decreaseQuantity: 'Diminuer la quantité', increaseQuantity: 'Augmenter la quantité'
};
