export default {
  appName: 'AGENSY', welcomeEyebrow: 'AGENSY AFRICA', welcomeTitle: 'L’approvisionnement qui tient parole.', welcomeText: 'Des produits fiables, des prix garantis et une livraison suivie, partout où votre commerce avance.', getStarted: 'Commencer', alreadyAccount: 'J’ai déjà un compte',
  phoneTitle: 'Votre numéro WhatsApp', phoneText: 'Nous vous envoyons un code de vérification pour sécuriser votre compte.', phoneLabel: 'Numéro WhatsApp', continue: 'Continuer', otpTitle: 'Vérifiez votre numéro', otpText: 'Saisissez le code à 6 chiffres envoyé sur WhatsApp.', otpLabel: 'Code de vérification', verify: 'Vérifier', resend: 'Renvoyer le code', demoHint: 'En démo, utilisez 123456.',
  profileTitle: 'Parlons de votre commerce', profileText: 'Ces informations permettent de préparer vos commandes et vos factures.', businessName: 'Nom du commerce', managerName: 'Nom du responsable', businessType: 'Type de commerce', country: 'Pays', ncc: 'Numéro de compte contribuable (NCC)', formal: 'Commerce formel', informal: 'Commerce informel', saveProfile: 'Enregistrer mon profil', profileRequired: 'Veuillez renseigner les champs obligatoires.',
  greeting: 'Bonjour', home: 'Accueil', catalog: 'Catalogue', order: 'Commande', tracking: 'Suivi', account: 'Compte', newOrder: 'Nouvelle commande', heroTitle: 'Votre approvisionnement, sans surprise.', heroText: 'Produits sélectionnés, prix mensuels garantis, livraison intégrée.', availableProducts: 'Produits disponibles', recentOrders: 'Commandes récentes', seeAll: 'Voir toutes', search: 'Rechercher un produit', monthlyGuarantee: 'Prix garanti ce mois', noProducts: 'Aucun produit ne correspond à votre recherche.',
  orderDetails: 'Votre commande', quantity: 'Quantité', minimum: 'Minimum', productSubtotal: 'Sous-total produits', serviceFee: 'Frais de service Agensy', delivery: 'Livraison', toConfirm: 'À confirmer', estimatedTotal: 'Total estimatif', deliveryNote: 'Le montant et la date de livraison seront confirmés par un opérateur avant paiement.', deliveryAddress: 'Adresse de livraison', deliveryPlaceholder: 'Ex. Cocody, Abidjan', instructions: 'Instructions de livraison', instructionsPlaceholder: 'Ex. Appelez avant de livrer', when: 'Quand souhaitez-vous être livré ?', asap: 'Dès que possible', scheduled: 'À une date précise', recurring: 'Récurrente', weekly: 'Chaque semaine', monthly: 'Chaque mois', sendOrder: 'Envoyer la commande', orderSent: 'Commande envoyée', orderSentText: 'Agensy répondra sous 24 heures. Vous serez informé ici et sur WhatsApp.',
  myOrders: 'Mes commandes', noOrders: 'Vous n’avez pas encore de commande.', startOrder: 'Créer une commande', draft: 'Brouillon', submitted: 'Envoyée', accepted: 'Acceptée', paid: 'Payée', delivered: 'Livrée', cancelled: 'Annulée', awaitingValidation: 'Validation Agensy en cours', payNow: 'Payer maintenant', paymentAvailable: 'Votre lien Jeko est disponible.', trackOrder: 'Suivre la commande', cancelOrder: 'Annuler la commande', cancelConfirm: 'Voulez-vous annuler cette commande ?', orderCancelled: 'Commande annulée',
  notifications: 'Notifications', noNotifications: 'Aucune notification pour le moment.', markAllRead: 'Tout marquer comme lu', invoices: 'Factures FNE', noInvoices: 'Vos factures certifiées apparaîtront ici.', downloadInvoice: 'Télécharger le PDF', accountTitle: 'Votre commerce', profileIncomplete: 'Profil à compléter', businessInformation: 'Informations du commerce', notificationPrefs: 'Notifications et WhatsApp', languageCurrency: 'Langue et devise', help: 'Aide', signOut: 'Se déconnecter', language: 'Langue', currency: 'Devise d’affichage', french: 'Français', english: 'English', xof: 'Franc CFA (XOF)', eur: 'Euro (EUR)', usd: 'Dollar US (USD)', save: 'Enregistrer', close: 'Fermer',
  error: 'Une erreur est survenue', networkError: 'Impossible de joindre Agensy. Vérifiez votre connexion.', required: 'Ce champ est requis.', pricePer: '{{price}}/{{unit}}', orderCount: '{{count}} commande', orderCount_plural: '{{count}} commandes'
};
