import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, FlatList, Image, SafeAreaView, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { StatusBar as ExpoStatusBar } from 'expo-status-bar';
import * as Location from 'expo-location';
import { ArrowLeft, Bell, ChevronRight, ClipboardList, FileText, Home, MapPin, Minus, PackageSearch, Plus, Search, ShoppingBag, UserRound } from 'lucide-react-native';
import { formatMoney, translate } from './src/i18n';

const API = process.env.EXPO_PUBLIC_API_URL || 'http://localhost:4000';
const BRAND_LOGO = `${API}/assets/branding/logo`;
const MAPBOX_ACCESS_TOKEN = process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN || '';
const statuses = ['draft', 'submitted', 'adjusted', 'accepted', 'paid', 'delivered', 'cancelled'];
const legacyBusinessTypes = { Boutique: 'shop', 'Restaurant / maquis': 'restaurant', Hôtel: 'hotel', Cantine: 'canteen', Revendeur: 'reseller' };

const AppIcon = ({ Icon, color = '#143f32', size = 22 }) => <Icon color={color} size={size} strokeWidth={1.25}/>;
const Button = ({ label, onPress, secondary, disabled }) => <TouchableOpacity accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={[s.button, secondary && s.buttonSecondary, disabled && s.disabled]}><Text style={[s.buttonText, secondary && s.buttonSecondaryText]}>{label}</Text></TouchableOpacity>;
const Field = ({ label, value, onChangeText, placeholder, keyboardType = 'default', autoCapitalize = 'sentences', editable = true }) => <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} keyboardType={keyboardType} autoCapitalize={autoCapitalize} editable={editable} style={[s.input, !editable && s.inputDisabled]}/></View>;
const Choice = ({ label, active, onPress }) => <TouchableOpacity accessibilityRole="radio" accessibilityLabel={label} accessibilityState={{ selected: active }} onPress={onPress} style={[s.choice, active && s.choiceActive]}><Text style={[s.choiceText, active && s.choiceTextActive]}>{label}</Text></TouchableOpacity>;

function OtpInput({ value, onChange, t }) {
  const refs = useRef([]);
  const update = (index, raw) => {
    const digits = raw.replace(/\D/g, ''); const next = value.padEnd(4, ' ').split('');
    if (digits.length > 1) digits.slice(0, 4 - index).split('').forEach((digit, offset) => { next[index + offset] = digit; }); else next[index] = digits || ' ';
    onChange(next.join('').replace(/ /g, ''));
    if (digits && index < 3) refs.current[Math.min(3, index + digits.length)]?.focus();
  };
  return <View style={s.otpRow}>{[0, 1, 2, 3].map((index) => <TextInput accessibilityLabel={t('otpDigit', { number: index + 1 })} key={index} ref={(el) => { refs.current[index] = el; }} value={value[index] || ''} onChangeText={(text) => update(index, text)} onKeyPress={({ nativeEvent }) => nativeEvent.key === 'Backspace' && !value[index] && index > 0 && refs.current[index - 1]?.focus()} keyboardType="number-pad" maxLength={4} textContentType="oneTimeCode" style={s.otpInput}/>)}</View>;
}

function MapboxAddressField({ label, value, onChange, onSelect, placeholder, country, locale, t }) {
  const [results, setResults] = useState([]);
  const search = async (query) => {
    onChange(query);
    if (!MAPBOX_ACCESS_TOKEN || query.trim().length < 3) return setResults([]);
    try {
      const url = `https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(query)}.json?access_token=${MAPBOX_ACCESS_TOKEN}&autocomplete=true&language=${locale}${country ? `&country=${country}` : ''}`;
      const response = await fetch(url); const data = await response.json(); setResults(data.features?.slice(0, 4) || []);
    } catch { setResults([]); }
  };
  return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={search} placeholder={placeholder} style={s.input}/>{results.map((place) => <TouchableOpacity accessibilityRole="button" accessibilityLabel={place.place_name} key={place.id} style={s.addressResult} onPress={() => { onSelect(place); setResults([]); }}><MapPin color="#287050" size={22} strokeWidth={1.25}/><View style={s.addressResultCopy}><Text style={s.addressResultTitle}>{place.text}</Text><Text style={s.addressResultText}>{place.place_name}</Text></View><ChevronRight color="#6c7d73" size={20} strokeWidth={1.25}/></TouchableOpacity>)}{!MAPBOX_ACCESS_TOKEN && <Text style={s.hint}>{t('mapboxUnavailable')}</Text>}</View>;
}

function PhoneStep({ t, countryCode, setCountryCode, phone, setPhone, onContinue }) {
  return <View><Text style={s.brand}>{t('welcomeEyebrow')}</Text><Text style={s.pageTitle}>{t('phoneTitle')}</Text><Text style={s.muted}>{t('phoneText')}</Text><Text style={s.fieldLabel}>{t('phoneLabel')}</Text><View style={s.phoneRow}><TextInput accessibilityLabel={t('countryCode')} value={countryCode} onChangeText={setCountryCode} keyboardType="phone-pad" style={s.countryCode}/><TextInput accessibilityLabel={t('phoneLabel')} value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder={t('phonePlaceholder')} style={s.phoneInput}/></View><Text style={s.hint}>{t('phoneHint')}</Text><Button label={t('continue')} onPress={onContinue}/></View>;
}

function OtpStep({ t, code, setCode, onVerify }) {
  return <View><Text style={s.brand}>{t('welcomeEyebrow')}</Text><Text style={s.pageTitle}>{t('otpTitle')}</Text><Text style={s.muted}>{t('otpText')}</Text><Text style={s.fieldLabel}>{t('otpLabel')}</Text><OtpInput value={code} onChange={setCode} t={t}/><Text style={s.hint}>{t('otpHint')}</Text><Button label={t('verify')} onPress={onVerify} disabled={code.length !== 4}/></View>;
}

function AccountWelcome({ profile, t, onCatalog, onHome }) {
  return <View><Image source={{ uri: BRAND_LOGO }} style={{ width: 92, height: 92, borderRadius: 20, marginBottom: 20 }}/><Text style={s.brand}>{t('welcomeEyebrow')}</Text><Text style={s.welcomeTitle}>{t('accountWelcomeTitle', { name: profile.businessName || t('partner') })}</Text><Text style={s.welcomeText}>{t('accountWelcomeText')}</Text><View style={s.benefit}><Text style={s.benefitText}>✓ {t('deliveryAddressSaved')}</Text><Text style={s.benefitText}>✓ {t('whatsAppEnabled')}</Text><Text style={s.benefitText}>✓ {t('b2bInvoicingReady')}</Text></View><Button label={t('browseCatalogue')} onPress={onCatalog}/><Button label={t('goToHome')} secondary onPress={onHome}/></View>;
}

function ProfileWizard({ profile, setProfile, step, setStep, onSave, locale, onLocate, locating, t }) {
  const set = (key, value) => setProfile({ ...profile, [key]: value });
  const mapPreview = profile.mapLocation && MAPBOX_ACCESS_TOKEN ? `https://api.mapbox.com/styles/v1/mapbox/streets-v12/static/pin-s+db6733(${profile.mapLocation.longitude},${profile.mapLocation.latitude})/${profile.mapLocation.longitude},${profile.mapLocation.latitude},14/360x180?access_token=${MAPBOX_ACCESS_TOKEN}` : null;
  const steps = ['profileStepBusiness', 'profileStepContact', 'profileStepDelivery', 'profileStepBilling'].map(t);
  const valid = () => [
    profile.businessName && profile.businessType && profile.legalStatus,
    profile.managerName && profile.managerRole,
    profile.country && profile.city && profile.deliveryAddress,
    profile.country === 'CI' ? profile.ncc : profile.internationalId
  ][step];
  const next = () => { if (!valid()) return Alert.alert(t('requiredFields'), t('completeStep')); if (step < 3) setStep(step + 1); else onSave(); };
  return <ScrollView contentContainerStyle={s.profileScroll}><Text style={s.brand}>{t('welcomeEyebrow')}</Text><Text style={s.pageTitle}>{t('setupBusinessAccount')}</Text><Text style={s.muted}>{t('setupBusinessAccountText')}</Text><View style={s.stepper}>{steps.map((label, index) => <View key={label} style={s.stepItem}><View style={[s.stepDot, index <= step && s.stepDotActive]}><Text style={index <= step ? s.stepNumberActive : s.stepNumber}>{index + 1}</Text></View><Text style={[s.stepLabel, index === step && s.stepLabelActive]}>{label}</Text></View>)}</View>
    {step === 0 && <><Text style={s.sectionTitle}>{t('yourBusiness')}</Text><Field label={t('businessNameRequired')} value={profile.businessName} onChangeText={(v) => set('businessName', v)} placeholder={t('businessNamePlaceholder')}/><Text style={s.fieldLabel}>{t('businessTypeRequired')}</Text><View style={s.choices}>{['shop', 'restaurant', 'hotel', 'canteen', 'reseller'].map((item) => <Choice key={item} label={t(`businessType${item[0].toUpperCase()}${item.slice(1)}`)} active={profile.businessType === item} onPress={() => set('businessType', item)}/>)}</View><Text style={s.fieldLabel}>{t('businessStatusRequired')}</Text><View style={s.choices}><Choice label={t('formal')} active={profile.legalStatus === 'formal'} onPress={() => set('legalStatus', 'formal')}/><Choice label={t('informal')} active={profile.legalStatus === 'informal'} onPress={() => set('legalStatus', 'informal')}/></View></>}
    {step === 1 && <><Text style={s.sectionTitle}>{t('accountManager')}</Text><Field label={t('fullNameRequired')} value={profile.managerName} onChangeText={(v) => set('managerName', v)} placeholder={t('fullNamePlaceholder')}/><Field label={t('roleRequired')} value={profile.managerRole} onChangeText={(v) => set('managerRole', v)} placeholder={t('rolePlaceholder')}/><Field label={t('businessEmailOptional')} value={profile.email} onChangeText={(v) => set('email', v)} keyboardType="email-address" autoCapitalize="none" placeholder={t('businessEmailPlaceholder')}/><Text style={s.hint}>{t('verifiedWhatsAppHint')}</Text></>}
    {step === 2 && <><Text style={s.sectionTitle}>{t('usualDeliveryAddress')}</Text><Text style={s.fieldLabel}>{t('deliveryAreaRequired')}</Text><View style={s.choices}><Choice label={t('ivoryCoast')} active={profile.country === 'CI'} onPress={() => set('country', 'CI')}/><Choice label={t('international')} active={profile.country === 'INTL'} onPress={() => set('country', 'INTL')}/></View><Button label={locating ? t('locating') : t('locateBusiness')} secondary disabled={locating} onPress={onLocate}/>{mapPreview && <Image source={{ uri: mapPreview }} style={{ width: '100%', height: 180, borderRadius: 12, marginTop: 14 }}/>}<Field label={t('cityRequired')} value={profile.city} onChangeText={(v) => set('city', v)} placeholder={t('cityPlaceholder')}/><MapboxAddressField label={t('addressDistrictRequired')} value={profile.deliveryAddress} onChange={(v) => set('deliveryAddress', v)} onSelect={(place) => { setProfile({ ...profile, deliveryAddress: place.place_name, city: profile.city || place.context?.find((item) => item.id.startsWith('place.'))?.text || place.text, mapLocation: { longitude: place.center?.[0], latitude: place.center?.[1] } }); }} country={profile.country === 'CI' ? 'ci' : ''} placeholder={t('addressDistrictPlaceholder')} locale={locale} t={t}/><Field label={t('landmarkOptional')} value={profile.landmark} onChangeText={(v) => set('landmark', v)} placeholder={t('landmarkPlaceholder')}/></>}
    {step === 3 && <><Text style={s.sectionTitle}>{t('billingInformation')}</Text>{profile.country === 'CI' ? <><Field label={t('nccRequired')} value={profile.ncc} onChangeText={(v) => set('ncc', v)} autoCapitalize="characters" placeholder={t('nccPlaceholder')}/><Text style={s.hint}>{t('nccHint')}</Text></> : <><Field label={t('taxIdRequired')} value={profile.internationalId} onChangeText={(v) => set('internationalId', v)} placeholder={t('taxIdPlaceholder')}/><Field label={t('billingCountryRequired')} value={profile.billingCountry} onChangeText={(v) => set('billingCountry', v)} placeholder={t('billingCountryPlaceholder')}/></>}</>}
    <View style={s.wizardActions}>{step > 0 && <Button label={t('back')} secondary onPress={() => setStep(step - 1)}/>}<Button label={step === 3 ? t('finishProfile') : t('continue')} onPress={next}/></View></ScrollView>;
}

function ProductCard({ product, onPress, money, t }) { return <TouchableOpacity accessibilityRole="button" accessibilityLabel={product.name} style={s.card} onPress={onPress}><Image source={{ uri: `${API}${product.image}` }} style={s.image}/><View style={s.cardBody}><Text style={s.productName}>{product.name}</Text><Text style={s.muted}>{product.unitLabel}</Text><Text style={s.price}>{t('pricePer', { price: money(product.unitPrice), unit: product.unit })}</Text><Text style={s.guarantee}>{t('monthlyGuarantee')}</Text></View></TouchableOpacity>; }
function OrderRow({ order, money, onPress, t }) { return <TouchableOpacity accessibilityRole="button" accessibilityLabel={`${order.product.name}, ${t(order.status)}`} onPress={onPress} style={s.order}><View style={s.orderCopy}><Text style={s.productName}>{order.product.name}</Text><Text style={s.muted}>{order.quantity} × {order.product.unitLabel}</Text></View><View style={s.orderMeta}><Text style={s.badge}>{t(order.status)}</Text><Text style={s.price}>{money(order.pricing.total)}</Text></View><ChevronRight color="#6c7d73" size={22} strokeWidth={1.25}/></TouchableOpacity>; }

export default function App() {
  const [locale, setLocale] = useState('fr'); const [currency, setCurrency] = useState('XOF'); const t = (key, values) => translate(locale, key, values);
  const [stage, setStage] = useState('phone'); const [screen, setScreen] = useState('home'); const [countryCode, setCountryCode] = useState('+225'); const [phone, setPhone] = useState(''); const [code, setCode] = useState(''); const [customerId, setCustomerId] = useState(''); const [accessToken, setAccessToken] = useState(''); const [profileStep, setProfileStep] = useState(0);
  const [profile, setProfile] = useState({ businessName: '', businessType: '', legalStatus: 'formal', managerName: '', managerRole: '', email: '', country: 'CI', city: '', deliveryAddress: '', landmark: '', ncc: '', internationalId: '', billingCountry: '' });
  const [locating, setLocating] = useState(false);
  const [products, setProducts] = useState([]); const [orders, setOrders] = useState([]); const [notices, setNotices] = useState([]); const [invoices, setInvoices] = useState([]); const [cart, setCart] = useState(null); const [query, setQuery] = useState(''); const [address, setAddress] = useState(''); const [instructions, setInstructions] = useState(''); const [schedule, setSchedule] = useState('asap'); const [scheduleDate, setScheduleDate] = useState(''); const [frequency, setFrequency] = useState('weekly'); const [whatsApp, setWhatsApp] = useState(true);
  const money = (value) => formatMoney(value, currency, locale); const fullPhone = `${countryCode.replace(/\s/g, '')}${phone.replace(/\D/g, '')}`;
  const api = (path, options = {}) => fetch(`${API}/v1/${path}`, { ...options, headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json', ...(options.headers || {}) } });
  const fetchAll = async () => { try { const [p, o, n, i] = await Promise.all([fetch(`${API}/v1/products`).then((r) => r.json()), api('orders').then((r) => r.json()), api('notifications').then((r) => r.json()), api('invoices').then((r) => r.json())]); setProducts(p); setOrders(o); setNotices(n); setInvoices(i); } catch { /* The user may continue browsing cached state when offline. */ } };
  useEffect(() => { if (stage === 'app' && accessToken) fetchAll(); }, [stage, accessToken]);
  const requestOtp = async () => { if (!/^\+?[0-9]{8,16}$/.test(fullPhone)) return Alert.alert(t('error'), t('invalidWhatsAppNumber')); try { const response = await fetch(`${API}/v1/auth/request-otp`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phone: fullPhone }) }); if (!response.ok) throw Error(); setStage('otp'); } catch { Alert.alert(t('error'), t('networkError')); } };
  const verifyOtp = async () => { if (code.length !== 4) return; try { const response = await fetch(`${API}/v1/auth/verify-otp`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ phone: fullPhone, code }) }); const data = await response.json(); if (!response.ok) throw Error(); setCustomerId(data.customer.id); setAccessToken(data.accessToken); if (data.customer.profileCompleted) setStage('app'); else { setProfile({ ...profile, ...data.customer, businessType: legacyBusinessTypes[data.customer.businessType] || data.customer.businessType || '', country: data.customer.country || 'CI' }); setProfileStep(0); setStage('profile'); } } catch { Alert.alert(t('error'), t('otpText')); } };
  const saveProfile = async () => { try { const response = await api(`customers/${customerId}/profile`, { method: 'PUT', body: JSON.stringify(profile) }); if (!response.ok) throw Error(); setStage('accountWelcome'); } catch { Alert.alert(t('error'), t('networkError')); } };
  const locateCommerce = async () => { try { setLocating(true); const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') return Alert.alert(t('error'), t('locationPermissionRequired')); const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); const mapLocation = { latitude: position.coords.latitude, longitude: position.coords.longitude }; let address = ''; let city = ''; if (MAPBOX_ACCESS_TOKEN) { const url = `https://api.mapbox.com/geocoding/v5/mapbox.places/${mapLocation.longitude},${mapLocation.latitude}.json?access_token=${MAPBOX_ACCESS_TOKEN}&language=${locale}`; const response = await fetch(url); const data = await response.json(); const place = data.features?.[0]; address = place?.place_name || ''; city = place?.context?.find((item) => item.id.startsWith('place.'))?.text || place?.text || ''; } setProfile((current) => ({ ...current, mapLocation, deliveryAddress: address || current.deliveryAddress, city: city || current.city })); } catch { Alert.alert(t('error'), t('locationNotFound')); } finally { setLocating(false); } };
  const submit = async () => { if (!cart || !address) return Alert.alert(t('error'), t('required')); const scheduleData = { type: schedule, ...(schedule === 'scheduled' ? { date: scheduleDate } : {}), ...(schedule === 'recurring' ? { frequency } : {}) }; if (schedule === 'scheduled' && !scheduleDate) return Alert.alert(t('error'), t('deliveryDateRequired')); try { const response = await api('orders', { method: 'POST', body: JSON.stringify({ productId: cart.id, quantity: cart.quantity, deliveryAddress: { label: address }, instructions, schedule: scheduleData }) }); const order = await response.json(); if (!response.ok) throw Error(); const submitted = await api(`orders/${order.id}/submit`, { method: 'POST' }); if (!submitted.ok) throw Error(); setCart(null); setScreen('orders'); await fetchAll(); Alert.alert(t('orderSent'), t('orderSentText')); } catch { Alert.alert(t('error'), t('networkError')); } };
  const filtered = useMemo(() => products.filter((product) => product.name.toLowerCase().includes(query.toLowerCase())), [products, query]);
  if (stage !== 'app') return <SafeAreaView style={s.safe}><ExpoStatusBar style="dark"/><View style={s.onboard}>{stage === 'phone' && <PhoneStep t={t} countryCode={countryCode} setCountryCode={setCountryCode} phone={phone} setPhone={setPhone} onContinue={requestOtp}/>} {stage === 'otp' && <OtpStep t={t} code={code} setCode={setCode} onVerify={verifyOtp}/>} {stage === 'profile' && <ProfileWizard profile={profile} setProfile={setProfile} step={profileStep} setStep={setProfileStep} onSave={saveProfile} locale={locale} onLocate={locateCommerce} locating={locating} t={t}/>} {stage === 'accountWelcome' && <AccountWelcome profile={profile} t={t} onCatalog={() => { setScreen('catalog'); setStage('app'); }} onHome={() => setStage('app')}/>}</View></SafeAreaView>;
  const productCard = ({ item }) => <ProductCard product={item} money={money} t={t} onPress={() => { setCart({ ...item, quantity: item.minQuantity }); setAddress(profile.deliveryAddress || ''); setScreen('cart'); }}/>;
  const cartTotal = cart ? cart.unitPrice * cart.unitContent * cart.quantity + 2000 : 0;
  let body;
  if (screen === 'home') body = <ScrollView><View style={s.hero}><Text style={s.brandLight}>{t('welcomeEyebrow')}</Text><Text style={s.heroTitle}>{t('heroTitle')}</Text><Text style={s.heroText}>{t('heroText')}</Text><Button label={t('newOrder')} onPress={() => setScreen('catalog')}/></View><Header label={t('availableProducts')} /><FlatList horizontal data={products.slice(0, 5)} renderItem={productCard} keyExtractor={(p) => p.id} showsHorizontalScrollIndicator={false}/><Header label={t('recentOrders')} action={t('seeAll')} onPress={() => setScreen('orders')}/>{orders.slice(0, 3).map((order) => <OrderRow key={order.id} order={order} money={money} t={t} onPress={() => { setCart(order); setScreen('orderDetail'); }}/>)}</ScrollView>;
  if (screen === 'catalog') body = <View style={s.catalog}><View style={s.searchWrap}><Search color="#426052" size={22} strokeWidth={1.25}/><TextInput accessibilityLabel={t('search')} style={s.search} placeholder={t('search')} value={query} onChangeText={setQuery}/></View><FlatList data={filtered} renderItem={productCard} keyExtractor={(p) => p.id} ListEmptyComponent={<Text style={s.empty}>{t('noProducts')}</Text>}/></View>;
  if (screen === 'cart' && cart) body = <ScrollView contentContainerStyle={s.scrollContent}><Image source={{ uri: `${API}${cart.image}` }} style={s.feature}/><Text style={s.pageTitle}>{cart.name}</Text><Text style={s.muted}>{cart.unitLabel}</Text><View style={s.quantity}><TouchableOpacity accessibilityRole="button" accessibilityLabel={t('decreaseQuantity')} style={s.quantityControl} onPress={() => setCart({ ...cart, quantity: Math.max(cart.minQuantity, cart.quantity - 1) })}><AppIcon Icon={Minus}/></TouchableOpacity><View><Text style={s.quantityText}>{cart.quantity}</Text><Text style={s.muted}>{t('quantityRange', { min: cart.minQuantity, max: cart.maxQuantity })}</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel={t('increaseQuantity')} style={s.quantityControl} onPress={() => setCart({ ...cart, quantity: Math.min(cart.maxQuantity, cart.quantity + 1) })}><AppIcon Icon={Plus}/></TouchableOpacity></View><Field label={t('deliveryAddress')} value={address} onChangeText={setAddress} placeholder={t('deliveryPlaceholder')}/><Field label={t('instructions')} value={instructions} onChangeText={setInstructions} placeholder={t('instructionsPlaceholder')}/><Text style={s.fieldLabel}>{t('when')}</Text><View style={s.choices}>{[['asap', t('asap')], ['scheduled', t('scheduled')], ['recurring', t('recurring')]].map(([value, label]) => <Choice key={value} label={label} active={schedule === value} onPress={() => setSchedule(value)}/>)}</View>{schedule === 'scheduled' && <Field label={t('preferredDateRequired')} value={scheduleDate} onChangeText={setScheduleDate} placeholder={t('datePlaceholder')} keyboardType="numbers-and-punctuation"/>}{schedule === 'recurring' && <><Text style={s.fieldLabel}>{t('frequency')}</Text><View style={s.choices}><Choice label={t('weekly')} active={frequency === 'weekly'} onPress={() => setFrequency('weekly')}/><Choice label={t('monthly')} active={frequency === 'monthly'} onPress={() => setFrequency('monthly')}/></View></>}<View style={s.summary}><Row label={t('productSubtotal')} value={money(cartTotal - 2000)}/><Row label={t('serviceFee')} value={money(2000)}/><Row label={t('delivery')} value={t('toConfirm')}/><View style={s.rule}/><Row label={t('estimatedTotal')} value={money(cartTotal)} strong/></View><Text style={s.hint}>{t('deliveryNote')}</Text><Button label={t('sendOrder')} onPress={submit}/></ScrollView>;
  if (screen === 'orders') body = <FlatList data={orders} onRefresh={fetchAll} refreshing={false} keyExtractor={(order) => order.id} renderItem={({ item }) => <OrderRow order={item} money={money} t={t} onPress={() => { setCart(item); setScreen('orderDetail'); }}/>} ListEmptyComponent={<View style={s.emptyWrap}><Text style={s.empty}>{t('noOrders')}</Text><Button label={t('startOrder')} onPress={() => setScreen('catalog')}/></View>}/>;
  if (screen === 'orderDetail' && cart) { const timelineStatuses = statuses.filter((state) => state !== 'cancelled'); const current = Math.max(0, timelineStatuses.indexOf(cart.status)); body = <ScrollView contentContainerStyle={s.scrollContent}><TouchableOpacity accessibilityRole="button" accessibilityLabel={t('myOrders')} onPress={() => setScreen('orders')} style={s.backLink}><ArrowLeft color="#d76531" size={22} strokeWidth={1.25}/><Text style={s.link}>{t('myOrders')}</Text></TouchableOpacity><Text style={s.pageTitle}>{cart.product?.name || cart.name}</Text><Text style={s.badge}>{t(cart.status)}</Text><View style={s.timeline}>{timelineStatuses.map((state, index) => <View key={state} style={s.timelineRow}><View style={[s.dot, index <= current && s.dotActive]}/><Text style={index <= current ? s.strong : s.muted}>{t(state)}</Text></View>)}</View>{cart.pricing && <View style={s.summary}><Row label={t('estimatedTotal')} value={money(cart.pricing.total)} strong/></View>}{cart.status === 'accepted' && <><Text style={s.hint}>{t('paymentAvailable')}</Text><Button label={t('payNow')} onPress={() => Alert.alert(t('payNow'), cart.payment?.checkoutUrl || t('paymentAvailable'))}/></>}</ScrollView>; }
  if (screen === 'notifications') body = <FlatList data={notices} keyExtractor={(notice) => notice.id} renderItem={({ item }) => <View style={s.notice}><Text style={s.productName}>{item.title}</Text><Text style={s.muted}>{item.body}</Text></View>} ListEmptyComponent={<Text style={s.empty}>{t('noNotifications')}</Text>}/>;
  if (screen === 'invoices') body = <FlatList data={invoices} keyExtractor={(invoice) => invoice.id} renderItem={({ item }) => <View style={s.order}><Text style={s.productName}>{item.id}</Text><Text style={s.price}>{money(item.amount)}</Text></View>} ListEmptyComponent={<Text style={s.empty}>{t('noInvoices')}</Text>}/>;
  if (screen === 'account') body = <ScrollView contentContainerStyle={s.scrollContent}><View style={s.profileCard}><View style={s.avatar}><UserRound color="#185c40" size={28} strokeWidth={1.25}/></View><Text style={s.productName}>{profile.businessName || t('accountTitle')}</Text><Text style={s.muted}>{profile.businessType ? t(`businessType${profile.businessType[0].toUpperCase()}${profile.businessType.slice(1)}`) : t('profileIncomplete')}</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel={t('editBusinessProfile')} style={s.setting} onPress={() => { setProfileStep(0); setStage('profile'); }}><Text style={s.settingText}>{t('editBusinessProfile')}</Text><ChevronRight color="#426052" size={22} strokeWidth={1.25}/></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel={t('invoices')} style={s.setting} onPress={() => setScreen('invoices')}><Text style={s.settingText}>{t('invoices')}</Text><FileText color="#426052" size={22} strokeWidth={1.25}/></TouchableOpacity><View style={s.setting}><Text style={s.settingText}>{t('notificationPrefs')}</Text><Switch accessibilityLabel={t('notificationPrefs')} value={whatsApp} onValueChange={setWhatsApp}/></View><Text style={s.fieldLabel}>{t('language')}</Text><View style={s.choices}><Choice label={t('french')} active={locale === 'fr'} onPress={() => setLocale('fr')}/><Choice label={t('english')} active={locale === 'en'} onPress={() => setLocale('en')}/></View><Text style={s.fieldLabel}>{t('currency')}</Text><View style={s.choices}>{['XOF', 'EUR', 'USD'].map((value) => <Choice key={value} label={value} active={currency === value} onPress={() => setCurrency(value)}/>)}</View></ScrollView>;
  const titles = { home: t('greeting'), catalog: t('catalog'), cart: t('orderDetails'), orders: t('myOrders'), orderDetail: t('trackOrder'), notifications: t('notifications'), invoices: t('invoices'), account: t('account') };
  return <SafeAreaView style={s.safe}><ExpoStatusBar style="dark"/><View style={s.top}><View><Text style={s.brand}>{t('appName')}</Text><Text style={s.title}>{titles[screen]}</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel={t('notifications')} onPress={() => setScreen('notifications')} style={s.bell}><Bell color="#143f32" size={22} strokeWidth={1.25}/></TouchableOpacity></View><View style={s.content}>{body}</View><View style={s.tabs}><Tab Icon={Home} label={t('home')} active={screen === 'home'} onPress={() => setScreen('home')}/><Tab Icon={PackageSearch} label={t('catalog')} active={screen === 'catalog'} onPress={() => setScreen('catalog')}/><Tab Icon={ShoppingBag} label={t('order')} active={screen === 'cart'} onPress={() => setScreen('cart')}/><Tab Icon={ClipboardList} label={t('tracking')} active={screen === 'orders'} onPress={() => setScreen('orders')}/><Tab Icon={UserRound} label={t('account')} active={screen === 'account'} onPress={() => setScreen('account')}/></View></SafeAreaView>;
}

function Tab({ Icon, label, active, onPress }) { const color = active ? '#d76531' : '#587062'; return <TouchableOpacity accessibilityRole="tab" accessibilityLabel={label} accessibilityState={{ selected: active }} onPress={onPress} style={s.tab}><Icon color={color} size={23} strokeWidth={1.25}/><Text style={[s.tabLabel, active && s.accent]}>{label}</Text></TouchableOpacity>; }
function Header({ label, action, onPress }) { return <View style={s.heading}><Text style={s.sectionTitle}>{label}</Text>{action && <TouchableOpacity accessibilityRole="button" accessibilityLabel={action} onPress={onPress} style={s.headerAction}><Text style={s.link}>{action}</Text><ChevronRight color="#d76531" size={18} strokeWidth={1.25}/></TouchableOpacity>}</View>; }
function Row({ label, value, strong }) { return <View style={s.row}><Text style={strong && s.strong}>{label}</Text><Text style={strong && s.strong}>{value}</Text></View>; }

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f7f8f5', paddingTop: StatusBar.currentHeight || 0 },
  onboard: { flex: 1, padding: 24, justifyContent: 'center' }, profileScroll: { paddingBottom: 32 }, scrollContent: { paddingBottom: 32 }, content: { flex: 1, paddingHorizontal: 20 },
  top: { paddingHorizontal: 20, paddingVertical: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, brand: { fontSize: 12, lineHeight: 16, fontWeight: '800', letterSpacing: 1.4, color: '#b65024' }, brandLight: { fontSize: 12, lineHeight: 16, fontWeight: '800', letterSpacing: 1.4, color: '#d8eadc' }, title: { fontSize: 30, lineHeight: 36, fontWeight: '800', color: '#143f32' }, pageTitle: { fontSize: 30, lineHeight: 37, fontWeight: '800', color: '#143f32', marginTop: 14 }, welcomeTitle: { fontSize: 34, lineHeight: 41, fontWeight: '800', color: '#143f32' }, welcomeText: { color: '#4d6258', lineHeight: 25, fontSize: 17, marginVertical: 18 }, muted: { color: '#53675e', lineHeight: 23, fontSize: 16 },
  benefit: { gap: 12, backgroundColor: '#eef5ef', borderWidth: 1, borderColor: '#cfe0d2', padding: 18, borderRadius: 16, marginVertical: 10 }, benefitText: { color: '#185c40', fontSize: 16, lineHeight: 22, fontWeight: '700' }, button: { minHeight: 54, backgroundColor: '#c95c2d', paddingHorizontal: 20, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginTop: 14 }, buttonText: { color: '#ffffff', fontSize: 17, lineHeight: 22, fontWeight: '800' }, buttonSecondary: { backgroundColor: '#ffffff', borderWidth: 1.25, borderColor: '#287050' }, buttonSecondaryText: { color: '#185c40' }, disabled: { opacity: 0.48 },
  field: { marginTop: 20 }, fieldLabel: { fontSize: 15, lineHeight: 20, fontWeight: '700', color: '#284b3b', marginTop: 20, marginBottom: 8 }, input: { minHeight: 54, backgroundColor: '#ffffff', borderColor: '#b9ccc0', borderWidth: 1.25, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 12, fontSize: 17, color: '#143f32' }, inputDisabled: { backgroundColor: '#edf1ed' }, phoneRow: { flexDirection: 'row', gap: 12, alignItems: 'center' }, countryCode: { width: 96, minHeight: 54, backgroundColor: '#ffffff', borderColor: '#b9ccc0', borderWidth: 1.25, borderRadius: 14, paddingHorizontal: 14, fontSize: 17 }, phoneInput: { flex: 1, minHeight: 54, backgroundColor: '#ffffff', borderColor: '#b9ccc0', borderWidth: 1.25, borderRadius: 14, paddingHorizontal: 16, fontSize: 17 },
  otpRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, marginTop: 10 }, otpInput: { flex: 1, maxWidth: 64, aspectRatio: 1, backgroundColor: '#ffffff', borderColor: '#b9ccc0', borderWidth: 1.25, borderRadius: 14, textAlign: 'center', fontSize: 24, fontWeight: '800', color: '#143f32' }, hint: { fontSize: 14, color: '#53675e', lineHeight: 21, marginVertical: 16 },
  stepper: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 26 }, stepItem: { alignItems: 'center', flex: 1 }, stepDot: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#e1e8e2', alignItems: 'center', justifyContent: 'center' }, stepDotActive: { backgroundColor: '#c95c2d' }, stepNumber: { color: '#426052', fontWeight: '800', fontSize: 15 }, stepNumberActive: { color: '#ffffff', fontWeight: '800', fontSize: 15 }, stepLabel: { fontSize: 11, lineHeight: 14, color: '#53675e', marginTop: 7, textAlign: 'center' }, stepLabelActive: { color: '#143f32', fontWeight: '800' }, sectionTitle: { fontSize: 22, lineHeight: 28, fontWeight: '800', color: '#143f32' }, choices: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' }, choice: { minHeight: 46, backgroundColor: '#ffffff', borderWidth: 1.25, borderColor: '#b9ccc0', borderRadius: 23, paddingVertical: 10, paddingHorizontal: 16, justifyContent: 'center' }, choiceActive: { backgroundColor: '#e8f3eb', borderColor: '#287050' }, choiceText: { color: '#284b3b', fontSize: 16, lineHeight: 21 }, choiceTextActive: { color: '#185c40', fontWeight: '800' }, wizardActions: { marginTop: 28 },
  hero: { backgroundColor: '#143f32', padding: 24, borderRadius: 20, marginBottom: 28 }, heroTitle: { color: '#ffffff', fontSize: 30, fontWeight: '800', lineHeight: 37, marginTop: 10 }, heroText: { color: '#d8eadc', fontSize: 16, lineHeight: 24, marginVertical: 14 }, heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }, headerAction: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 2 }, link: { color: '#b65024', fontSize: 16, fontWeight: '800' }, accent: { color: '#b65024', fontWeight: '800' },
  card: { width: 244, minHeight: 286, backgroundColor: '#ffffff', borderRadius: 18, marginRight: 14, overflow: 'hidden', borderWidth: 1.25, borderColor: '#d8e4da' }, image: { height: 138, width: '100%' }, cardBody: { padding: 16 }, productName: { fontSize: 18, lineHeight: 24, fontWeight: '800', color: '#143f32' }, price: { fontSize: 16, lineHeight: 22, fontWeight: '800', color: '#185c40', marginTop: 10 }, guarantee: { fontSize: 13, lineHeight: 19, color: '#9b4d27', marginTop: 7 },
  catalog: { flex: 1 }, searchWrap: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#ffffff', borderColor: '#b9ccc0', borderWidth: 1.25, borderRadius: 14, paddingHorizontal: 16, marginBottom: 14 }, search: { flex: 1, minHeight: 52, fontSize: 17, color: '#143f32' }, feature: { width: '100%', height: 236, borderRadius: 18, marginBottom: 16 }, quantity: { backgroundColor: '#ffffff', borderColor: '#d8e4da', borderWidth: 1.25, borderRadius: 16, padding: 14, marginVertical: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, quantityControl: { width: 52, height: 52, borderRadius: 14, borderWidth: 1.25, borderColor: '#b9ccc0', alignItems: 'center', justifyContent: 'center', backgroundColor: '#ffffff' }, quantityText: { fontSize: 24, lineHeight: 30, fontWeight: '800', textAlign: 'center', color: '#143f32' },
  summary: { backgroundColor: '#ffffff', borderColor: '#d8e4da', borderWidth: 1.25, borderRadius: 16, padding: 18, marginTop: 22 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginBottom: 14 }, rule: { height: 1, backgroundColor: '#d8e4da', marginBottom: 14 }, strong: { fontWeight: '800', fontSize: 18, color: '#143f32' }, order: { minHeight: 92, backgroundColor: '#ffffff', borderRadius: 16, borderWidth: 1.25, borderColor: '#d8e4da', padding: 16, marginBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, orderCopy: { flex: 1 }, orderMeta: { alignItems: 'flex-end' }, notice: { backgroundColor: '#ffffff', borderRadius: 16, borderWidth: 1.25, borderColor: '#d8e4da', padding: 18, marginBottom: 12 }, badge: { fontSize: 14, lineHeight: 20, color: '#8b4c1d', fontWeight: '800', textAlign: 'right' },
  bell: { width: 48, height: 48, borderRadius: 14, borderWidth: 1.25, borderColor: '#b9ccc0', backgroundColor: '#ffffff', alignItems: 'center', justifyContent: 'center' }, tabs: { minHeight: 76, backgroundColor: '#ffffff', borderTopWidth: 1.25, borderColor: '#d8e4da', flexDirection: 'row', paddingHorizontal: 8 }, tab: { flex: 1, minHeight: 72, alignItems: 'center', justifyContent: 'center', gap: 4 }, tabLabel: { fontSize: 12, lineHeight: 16, color: '#53675e', textAlign: 'center' }, emptyWrap: { marginTop: 72, alignItems: 'center' }, empty: { color: '#53675e', fontSize: 16, lineHeight: 24, textAlign: 'center', marginTop: 50 },
  timeline: { backgroundColor: '#ffffff', borderColor: '#d8e4da', borderWidth: 1.25, padding: 18, borderRadius: 16, marginTop: 18 }, timelineRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10 }, dot: { height: 12, width: 12, borderRadius: 6, backgroundColor: '#d8e4da' }, dotActive: { backgroundColor: '#c95c2d' }, backLink: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 8, alignSelf: 'flex-start' },
  profileCard: { backgroundColor: '#ffffff', borderColor: '#d8e4da', borderWidth: 1.25, padding: 24, borderRadius: 18, alignItems: 'center', marginBottom: 16 }, avatar: { height: 64, width: 64, borderRadius: 18, backgroundColor: '#e8f3eb', alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, setting: { minHeight: 60, paddingHorizontal: 18, backgroundColor: '#ffffff', borderWidth: 1.25, borderColor: '#d8e4da', borderRadius: 14, marginBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, settingText: { flex: 1, color: '#143f32', fontSize: 17, lineHeight: 22, fontWeight: '700' },
  addressResult: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#ffffff', borderWidth: 1.25, borderColor: '#d8e4da', borderRadius: 14, padding: 14, marginTop: 8 }, addressResultCopy: { flex: 1 }, addressResultTitle: { color: '#143f32', fontSize: 16, lineHeight: 21, fontWeight: '800' }, addressResultText: { color: '#53675e', fontSize: 14, lineHeight: 19, marginTop: 2 }
});
