import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, CheckCircle2, ClipboardList, FileText, LayoutDashboard, LogOut, Package, RefreshCw, SlidersHorizontal, Truck, Users, WalletCards } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000';
const money = (amount) => new Intl.NumberFormat('fr-CI').format(amount) + ' FCFA';
const statusLabels = { draft: 'Brouillon', submitted: 'À valider', adjusted: 'À confirmer', accepted: 'Acceptée', paid: 'Payée', delivered: 'Livrée', cancelled: 'Annulée' };
const Icon = ({ icon: Component, size = 20 }) => <Component size={size} strokeWidth={1.25} aria-hidden="true"/>;

function App() {
  const [orders, setOrders] = useState([]); const [products, setProducts] = useState([]); const [busy, setBusy] = useState('');
  const [token, setToken] = useState(sessionStorage.getItem('agensy_operator_token') || ''); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };
  useEffect(() => { let icon = document.querySelector("link[rel~='icon']"); if (!icon) { icon = document.createElement('link'); icon.rel = 'icon'; document.head.appendChild(icon); } icon.href = `${API}/assets/branding/logo`; }, []);
  const load = async () => { const [ordersResponse, productsResponse] = await Promise.all([fetch(`${API}/v1/orders`, { headers }), fetch(`${API}/v1/products`)]); const [nextOrders, nextProducts] = await Promise.all([ordersResponse.json(), productsResponse.json()]); if (!ordersResponse.ok || !Array.isArray(nextOrders)) throw new Error('Session expirée ou serveur indisponible.'); setOrders(nextOrders); setProducts(Array.isArray(nextProducts) ? nextProducts : []); };
  useEffect(() => { if (token) load().catch((loadError) => setError(loadError.message)); }, [token]);
  const login = async (event) => { event.preventDefault(); setError(''); const response = await fetch(`${API}/v1/admin/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) }); const data = await response.json(); if (!response.ok) return setError('Identifiants invalides.'); sessionStorage.setItem('agensy_operator_token', data.accessToken); setToken(data.accessToken); };
  const logout = () => { sessionStorage.removeItem('agensy_operator_token'); setToken(''); setOrders([]); setProducts([]); setError(''); };
  const accept = async (order) => { const deliveryFee = Number(window.prompt('Frais de livraison (FCFA)', String(order.pricing.deliveryFee || 0))); const deliveryDate = window.prompt('Date de livraison (AAAA-MM-JJ)', order.deliveryDate || new Date(Date.now() + 172800000).toISOString().slice(0, 10)); if (!Number.isFinite(deliveryFee) || !deliveryDate) return; setBusy(order.id); try { const response = await fetch(`${API}/v1/admin/orders/${order.id}/accept`, { method: 'POST', headers, body: JSON.stringify({ deliveryFee, deliveryDate }) }); if (!response.ok) throw Error(); await load(); } catch { setError('La commande n’a pas pu être acceptée.'); } finally { setBusy(''); } };
  const adjust = async (order) => { const deliveryFee = Number(window.prompt('Nouveaux frais de livraison (FCFA)', String(order.pricing.deliveryFee || 0))); const deliveryDate = window.prompt('Nouvelle date de livraison (AAAA-MM-JJ)', order.deliveryDate || ''); const note = window.prompt('Motif de l’ajustement'); if (!Number.isFinite(deliveryFee) || !deliveryDate || !note) return; setBusy(order.id); try { const response = await fetch(`${API}/v1/admin/orders/${order.id}/adjust`, { method: 'POST', headers, body: JSON.stringify({ deliveryFee, deliveryDate, note }) }); if (!response.ok) throw Error(); await load(); } catch { setError('L’ajustement n’a pas pu être enregistré.'); } finally { setBusy(''); } };
  const issueInvoice = async (order) => { if (!order.invoiceId) return setError('La facture n’est pas encore disponible.'); const invoiceNumber = window.prompt('Numéro de facture manuel'); if (!invoiceNumber) return; const pdfUrl = window.prompt('Lien PDF de la facture (optionnel)') || ''; setBusy(order.id); try { const issued = await fetch(`${API}/v1/admin/invoices/${order.invoiceId}/issue`, { method: 'POST', headers, body: JSON.stringify({ invoiceNumber, pdfUrl }) }); if (!issued.ok) throw Error(); if (window.confirm('Ouvrir WhatsApp avec le message de facture ?')) { const shared = await fetch(`${API}/v1/admin/invoices/${order.invoiceId}/whatsapp-share`, { method: 'POST', headers }); const data = await shared.json(); if (shared.ok) window.open(data.whatsAppUrl, '_blank', 'noopener,noreferrer'); } await load(); } catch { setError('La facture n’a pas pu être émise.'); } finally { setBusy(''); } };
  const deliver = async (order) => { setBusy(order.id); try { const response = await fetch(`${API}/v1/admin/orders/${order.id}/deliver`, { method: 'POST', headers }); if (!response.ok) throw Error(); await load(); } catch { setError('La livraison n’a pas pu être confirmée.'); } finally { setBusy(''); } };

  if (!token) return <main className="login"><section className="loginIntro"><p className="eyebrow">AGENSY AFRICA</p><h1>L’approvisionnement sous contrôle.</h1><p>Un espace simple pour traiter les commandes, les paiements et les livraisons.</p><div className="loginPoints"><span><CheckCircle2/> Suivi des commandes</span><span><CheckCircle2/> Validation en quelques étapes</span><span><CheckCircle2/> Facturation centralisée</span></div></section><section className="loginPanel"><p className="eyebrow">ESPACE SÉCURISÉ</p><h2>Accès opérateur</h2><p>Connectez-vous pour gérer les opérations Agensy.</p><form onSubmit={login}><label>Identifiant<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" required/></label><label>Mot de passe<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" required/></label><button className="primaryButton" type="submit">Se connecter <Icon icon={ArrowUpRight} size={19}/></button>{error && <p className="error" role="alert">{error}</p>}</form></section></main>;

  const pendingCount = orders.filter((order) => ['submitted', 'adjusted'].includes(order.status)).length;
  const paidTotal = orders.filter((order) => order.status === 'paid').reduce((sum, order) => sum + order.pricing.total, 0);
  return <main className="appShell"><aside className="sidebar"><div><img src={`${API}/assets/branding/logo`} alt="Agensy Africa" onError={(event) => event.currentTarget.style.display = 'none'}/><p className="brandName">Agensy Africa</p><p className="brandRole">Opérations B2B</p></div><nav aria-label="Navigation principale"><a className="active"><Icon icon={LayoutDashboard}/> Vue d’ensemble</a><a><Icon icon={ClipboardList}/> Commandes</a><a><Icon icon={Package}/> Catalogue</a><a><Icon icon={FileText}/> Factures</a><a><Icon icon={Users}/> Clients</a></nav><div className="sidebarFoot"><span><span className="liveDot"/> Service actif</span><button className="sidebarButton" onClick={logout}><Icon icon={LogOut}/> Déconnexion</button></div></aside>
    <section className="dashboard"><header className="pageHeader"><div><p className="eyebrow">TABLEAU DE BORD</p><h1>Bonjour, équipe Agensy</h1><p>Suivez les opérations prioritaires et gardez les livraisons en mouvement.</p></div><button className="secondaryButton" onClick={() => load().catch((loadError) => setError(loadError.message))}><Icon icon={RefreshCw}/> Actualiser</button></header>
      {error && <p className="error" role="alert">{error}</p>}
      <div className="stats"><article><span className="statIcon"><Icon icon={ClipboardList}/></span><div><b>{orders.length}</b><span>Commandes</span></div></article><article><span className="statIcon amber"><Icon icon={SlidersHorizontal}/></span><div><b>{pendingCount}</b><span>À traiter</span></div></article><article><span className="statIcon blue"><Icon icon={WalletCards}/></span><div><b>{money(paidTotal)}</b><span>Encaissements</span></div></article><article><span className="statIcon leaf"><Icon icon={Package}/></span><div><b>{products.length}</b><span>Produits actifs</span></div></article></div>
      <section className="panel"><div className="panelTitle"><div><p className="eyebrow">OPÉRATIONS</p><h2>Commandes récentes</h2><p>Le prix et la livraison sont confirmés avant paiement.</p></div><span className="tableCount">{orders.length} au total</span></div><div className="tableWrap"><table><thead><tr><th>Référence</th><th>Produit</th><th>Quantité</th><th>Total</th><th>Statut</th><th>Action</th></tr></thead><tbody>{orders.length ? orders.map((order) => <tr key={order.id}><td><code>{order.id}</code><small>{new Date(order.createdAt).toLocaleDateString('fr-FR')}</small></td><td><b>{order.product.name}</b><small>{order.product.unitLabel}</small></td><td>{order.quantity}</td><td><b>{money(order.pricing.total)}</b></td><td><em className={`status ${order.status}`}>{statusLabels[order.status]}</em></td><td><div className="rowActions">{order.status === 'submitted' && <><button disabled={busy === order.id} onClick={() => accept(order)}>Accepter</button><button className="textButton" disabled={busy === order.id} onClick={() => adjust(order)}>Ajuster</button></>}{order.status === 'paid' && <><button disabled={busy === order.id} onClick={() => issueInvoice(order)}>Facture</button><button className="textButton" disabled={busy === order.id} onClick={() => deliver(order)}>Livrer</button></>}{!['submitted', 'paid'].includes(order.status) && <span className="muted">Aucune action</span>}</div></td></tr>) : <tr><td colSpan="6" className="empty">Aucune commande pour le moment. Créez-en une depuis l’application mobile.</td></tr>}</tbody></table></div></section>
      <section className="panel catalog"><div className="panelTitle"><div><p className="eyebrow">CATALOGUE</p><h2>Produits actifs</h2></div><span className="tableCount">{products.length} références</span></div><div className="productList">{products.slice(0, 6).map((product) => <article key={product.id}><img src={`${API}${product.image}`} alt=""/><div><b>{product.name}</b><small>{money(product.unitPrice)}/{product.unit}</small></div><Icon icon={Truck} size={19}/></article>)}</div></section>
    </section>
  </main>;
}

createRoot(document.getElementById('root')).render(<App/>);
