import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000';
const money = (amount) => new Intl.NumberFormat('fr-CI').format(amount) + ' FCFA';
const status = { draft: 'Brouillon', submitted: 'Envoyée', adjusted: 'À ajuster', accepted: 'Acceptée', paid: 'Payée', delivered: 'Livrée', cancelled: 'Annulée' };

function App() {
  const [orders, setOrders] = useState([]); const [products, setProducts] = useState([]); const [busy, setBusy] = useState('');
  const [token, setToken] = useState(sessionStorage.getItem('agensy_operator_token') || ''); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };
  useEffect(() => { let icon = document.querySelector("link[rel~='icon']"); if (!icon) { icon = document.createElement('link'); icon.rel = 'icon'; document.head.appendChild(icon); } icon.href = `${API}/assets/branding/logo`; }, []);
  const load = async () => { const [o, p] = await Promise.all([fetch(`${API}/v1/orders`, { headers }).then(r => r.json()), fetch(`${API}/v1/products`).then(r => r.json())]); if (!Array.isArray(o)) throw new Error('Session expirée ou serveur indisponible.'); setOrders(o); setProducts(p); };
  useEffect(() => { if (token) load().catch(e => setError(e.message)); }, [token]);
  const login = async (event) => { event.preventDefault(); setError(''); const response = await fetch(`${API}/v1/admin/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) }); const data = await response.json(); if (!response.ok) return setError('Identifiants invalides.'); sessionStorage.setItem('agensy_operator_token', data.accessToken); setToken(data.accessToken); };
  const accept = async (order) => { const deliveryFee = Number(window.prompt('Frais de livraison (FCFA)', String(order.pricing.deliveryFee || 0))); const deliveryDate = window.prompt('Date de livraison (AAAA-MM-JJ)', order.deliveryDate || new Date(Date.now() + 172800000).toISOString().slice(0, 10)); if (!Number.isFinite(deliveryFee) || !deliveryDate) return; setBusy(order.id); try { const response = await fetch(`${API}/v1/admin/orders/${order.id}/accept`, { method: 'POST', headers, body: JSON.stringify({ deliveryFee, deliveryDate }) }); if (!response.ok) throw Error(); await load(); } finally { setBusy(''); } };
  const adjust = async (order) => { const deliveryFee = Number(window.prompt('Nouveaux frais de livraison (FCFA)', String(order.pricing.deliveryFee || 0))); const deliveryDate = window.prompt('Nouvelle date de livraison (AAAA-MM-JJ)', order.deliveryDate || ''); const note = window.prompt('Motif de l’ajustement'); if (!Number.isFinite(deliveryFee) || !deliveryDate || !note) return; setBusy(order.id); try { const response = await fetch(`${API}/v1/admin/orders/${order.id}/adjust`, { method: 'POST', headers, body: JSON.stringify({ deliveryFee, deliveryDate, note }) }); if (!response.ok) throw Error(); await load(); } finally { setBusy(''); } };
  const issueInvoice = async (order) => { if (!order.invoiceId) return setError('La facture n’est pas encore disponible.'); const invoiceNumber = window.prompt('Numéro de facture manuel'); if (!invoiceNumber) return; const pdfUrl = window.prompt('Lien PDF de la facture (optionnel)') || ''; setBusy(order.id); try { const issued = await fetch(`${API}/v1/admin/invoices/${order.invoiceId}/issue`, { method: 'POST', headers, body: JSON.stringify({ invoiceNumber, pdfUrl }) }); if (!issued.ok) throw Error(); if (window.confirm('Ouvrir WhatsApp avec le message de facture ?')) { const shared = await fetch(`${API}/v1/admin/invoices/${order.invoiceId}/whatsapp-share`, { method: 'POST', headers }); const data = await shared.json(); if (shared.ok) window.open(data.whatsAppUrl, '_blank', 'noopener,noreferrer'); } await load(); } finally { setBusy(''); } };
  const deliver = async (order) => { setBusy(order.id); try { await fetch(`${API}/v1/admin/orders/${order.id}/deliver`, { method: 'POST', headers }); await load(); } finally { setBusy(''); } };
  if (!token) return <main className="login"><section className="panel"><p className="eyebrow">AGENSY AFRICA</p><h2>Accès opérateur</h2><p>Connectez-vous pour gérer les commandes.</p><form onSubmit={login}><input value={username} onChange={e => setUsername(e.target.value)} placeholder="Identifiant" autoComplete="username" /><input value={password} onChange={e => setPassword(e.target.value)} placeholder="Mot de passe" type="password" autoComplete="current-password" /><button>Se connecter</button>{error && <p className="error">{error}</p>}</form></section></main>;
  return <main>
    <aside><img src={`${API}/assets/branding/logo`} alt="Agensy Africa" onError={(e) => e.currentTarget.style.display = 'none'} /><h1>Agensy</h1><p>Back-office</p><nav><a className="active">Commandes</a><a>Catalogue</a><a>Factures FNE</a><a>Clients</a></nav><small>Opérations · Côte d’Ivoire</small></aside>
    <section><header><div><p className="eyebrow">TABLEAU DE BORD</p><h2>Bonjour, équipe Agensy</h2><p>Validez les approvisionnements et gardez la livraison sous contrôle.</p></div><button onClick={() => load().catch(e => setError(e.message))}>Actualiser</button></header>
      {error && <p className="error">{error}</p>}<div className="stats"><article><b>{orders.length}</b><span>Commandes</span></article><article><b>{orders.filter(o => o.status === 'submitted').length}</b><span>À valider</span></article><article><b>{money(orders.filter(o => o.status === 'paid').reduce((x, o) => x + o.pricing.total, 0))}</b><span>Encaissements</span></article><article><b>{products.length}</b><span>Produits actifs</span></article></div>
      <div className="panel"><div className="panelTitle"><div><h3>Commandes récentes</h3><p>Le prix et la livraison sont confirmés avant paiement.</p></div></div><div className="tableWrap"><table><thead><tr><th>Référence</th><th>Produit</th><th>Quantité</th><th>Total</th><th>Statut</th><th>Action</th></tr></thead><tbody>{orders.length ? orders.map(o => <tr key={o.id}><td><code>{o.id}</code><small>{new Date(o.createdAt).toLocaleDateString('fr-FR')}</small></td><td>{o.product.name}<small>{o.product.unitLabel}</small></td><td>{o.quantity}</td><td>{money(o.pricing.total)}</td><td><em className={`status ${o.status}`}>{status[o.status]}</em></td><td>{o.status === 'submitted' && <><button disabled={busy === o.id} onClick={() => accept(o)}>Accepter</button><button disabled={busy === o.id} onClick={() => adjust(o)}>Ajuster</button></>}{o.status === 'paid' && <><button disabled={busy === o.id} onClick={() => issueInvoice(o)}>Facture</button><button disabled={busy === o.id} onClick={() => deliver(o)}>Livrer</button></>}{!['submitted', 'paid'].includes(o.status) && '—'}</td></tr>) : <tr><td colSpan="6" className="empty">Aucune commande pour le moment. Créez-en une depuis l’application mobile.</td></tr>}</tbody></table></div></div>
      <div className="panel catalog"><h3>Catalogue actif</h3><div className="productList">{products.slice(0, 6).map(p => <div key={p.id}><img src={`${API}${p.image}`} /><span><b>{p.name}</b><small>{money(p.unitPrice)}/{p.unit}</small></span></div>)}</div></div>
    </section>
  </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
